% input : q = [qST qTW qSW dqST dqTW dqSW]
% output : q_plus = [dqST dqSW]
function q_plus = Dyn_Knee_Strike(q)
global a1 b1 a2 b2 mH mS mT ls lt L g IK IS IT theta
% state
qST = q(1); qTW = q(2); qSW = q(3);
dqST = q(4); dqTW = q(5); dqSW = q(6);

% Fill Your Code
% M C G matrix
% A = [a1.^2.*mS+(a2+ls).^2.*mT+L.^2.*(mH+mS+mT)+(-1).*L.*((b1+lt).*mS+ ...
%   b2.*mT).*cos(qST+(-1).*qTW),b1.*(b1+lt).*mS+b2.^2.*mT+(-1).* ...
%   L.*(b1.*mS+b2.*mT).*cos(qST+(-1).*qTW);(-1).*L.*((b1+lt).* ...
%   mS+b2.*mT).*cos(qST+(-1).*qTW),b1.*(b1+lt).*mS+b2.^2.*mT];
% 
% B = [0,0,(a1.^2.*mS+(a2+ls).^2.*mT+L.^2.*(mH+mS+mT)+(-1).*L.*((b1+lt) ...
%   .*mS+b2.*mT).*cos(qST+(-1).*qTW)).*dqST+ ...
%   b1.*mS.*(b1+lt+(-1).*L.*cos(qST+(-1).*qTW)).*dqSW+(lt.*(b1+lt).*mS+b2.^2.*mT+(-1).*L.*(lt.*mS+b2.*mT).*cos( ...
%   qST+(-1).*qTW)).*dqTW;0,0,(-1).*L.*((b1+lt) ...
%   .*mS+b2.*mT).*cos(qST+(-1).*qTW).*dqST+b1.* ...
%   (b1+lt).*mS.*dqSW+(lt.*(b1+lt).*mS+b2.^2.*mT).* ...
%   dqTW];
A = [a1.^2.*mS+(a2+ls).^2.*mT+L.^2.*(mH+mS+mT)+(-1).*L.*((b1+lt).*mS+ ...
  b2.*mT).*cos(qST+(-1).*qSW),(b1+lt).^2.*mS+b2.^2.*mT+(-1).* ...
  L.*((b1+lt).*mS+b2.*mT).*cos(qST+(-1).*qSW);(-1).*L.*((b1+ ...
  lt).*mS+b2.*mT).*cos(qST+(-1).*qSW),(b1+lt).^2.*mS+b2.^2.* ...
  mT];
B = [0,0,(a1.^2.*mS+(a2+ls).^2.*mT+L.^2.*(mH+mS+mT)+(-1).*L.*((b1+lt) ...
  .*mS+b2.*mT).*cos(qST+(-1).*qTW)).*dqST+ ...
  b1.*mS.*(b1+lt+(-1).*L.*cos(qST+(-1).*qTW)).*dqSW+(lt.*(b1+lt).*mS+b2.^2.*mT+(-1).*L.*(lt.*mS+b2.*mT).*cos( ...
  qST+(-1).*qTW)).*dqTW;0,0,(-1).*L.*((b1+lt) ...
  .*mS+b2.*mT).*cos(qST+(-1).*qTW).*dqST+b1.* ...
  (b1+lt).*mS.*dqSW+(lt.*(b1+lt).*mS+b2.^2.*mT).* ...
  dqTW];

q_plus = A\B*[dqST dqTW dqSW]'*0.11;
% Finish
end